=== Authentication and Authorization

The Vert.x Auth module has very significant changes in Vert.x 4. The most notable is that the interface
`io.vertx.ext.auth.AuthProvider` is split into 2 newly added interfaces:

1. `io.vertx.ext.auth.authentication.AuthenticationProvider`
2. `io.vertx.ext.auth.authorization.AuthorizationProvider`

This change means that any provider is now able to perform either `authentication` and `authorization` independently.
This of course means that API changes had to be made, and your code may need to be migrated.

Although these are the most notorious changes, this guide does not replace the full detailed list of breaking changes
listed on the https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes#vertx-auth-1[Vert.x WIKI].

==== Migrate Authentication

The authentication mechanism is practically the same, the main change happens at the result level. Before the result
was a `User` object that was provider specific, while in Vert.x 4, it is always a single implementation:
`io.vertx.ext.auth.User`.

[source,java]
----
JsonObject authInfo = new JsonObject()
  .put("username", "john")
  .put("password", "super$ecret");

// Authenticate a user (3.x)
// omitting the error handling for brevity
provider.authenticate(authInfo, res -> {
   if (res.succeeded()) {
     // may require type casting for example on Oauth2
     User user = res.result();
   }
});

// Authenticate a user (4.x)
// omitting the error handling for brevity
provider.authenticate(authInfo, res -> {
   if (res.succeeded()) {
     // Never needs type casting
     User user = res.result();
   }
});
----

==== Migrate Authorization

Authorization is a new feature that you will find on Vert.x 4. Before you could only assert that a `User` was
authorized to perform some task on the `User` object itself (which implies the provider was responsible for both
authentication (authn) and authorization (authz)). Now the `User` is unaware of the provider, so it can be used on
different providers.

As an example, consider an application that checks if a `User` can use `Printer #1234`:

[source,java]
----
// Authorize a user (3.x)
// omitting the error handling for brevity
user.isAuthorized("printers:printer1234", res -> {
  if (res.succeeded()) {
    boolean hasAuthority = res.result();
    if (hasAuthority) {
      System.out.println("User has the authority");
    } else {
      System.out.println("User does not have the authority");
    }
  }
});
----

While this worked fine for `JDBCAuth`, `MongoAuth`, `ShiroAuth`, it did not work for more typical providers such as
`OAuth2` as the provider did not perform authorization checks. This is now possible by mixing the right provider:

[source,java]
----
// Authorize a user (4.x)
// omitting the error handling for brevity
provider.getAuthorizations(user, res -> {
  if (res.succeeded()) {
    if (PermissionBasedAuthorization.create("printer1234").match(user)) {
      System.out.println("User has the authority");
    } else {
      System.out.println("User does not have the authority");
    }
  }
});
----

NOTE: While before the permissions were very basic, the new API allows authorizations on `Roles`,
`Permissions`, `Logic Operations`, `WildCards` and any other implementations you may add.

==== Migrate Providers

Some providers have been deprecated too and replaced by others.

===== Apache Shiro Provider

Apache Shiro provider was a problematic provider for several reasons:

1. It is implemented in a blocking API style, which means that it will not scale as expected for a Vert.x  application
2. It relies on `ThreadLocal` storage which forces the provider to constantly lock and save and restore state, bringing
the overall performance down.

Shiro is used mostly for 2 cases and can be replaced by:

1. `PropertyFile{Authentication|Authorization}` for property file based authentication and authorization
2. `LDAPAuthentication` for LDAP Authentication

===== JDBC Provider

JDBC provider was a problematic provider because it is implemented in a blocking API style, which means that it will
not scale as expected for a Vert.x  application. JDBC auth can be replaced by:

1. `Sql{Authentication|Authorization}` for authn/authz

==== Migrate passwords

In Vert.x 3 providers that relied on managing the user data, would have their own format to store passwords.
In Vert.x 4 this is standardized on https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md[P-H-C].

Vert.x stores passwords securely. You can't just re-encode them in the new format. It is advisably to request the end
user of your application to renew the password during the application migration.

Create a password hash that is compatible with:

* Mongo
* JDBC
* Sql

Takes the following form:

[source,java]
----
// 4.0 only!
String hash = provider.hash(
  "pkdbf2", // hashing algorithm (OWASP recommended)
  VertxContextPRNG.current().nextString(32), // secure random salt
  "super$ecret" // password
);
----

This is quite low level, so in order to simplify your work, some providers have a utility helper that can
create new users:

* JDBCUserUtil
* MongoUserUtil
* SqlUserUtil

These helpers can create the user, roles and permissions directly on the target store, simplifying your work
for migrations.

=== Key management

Handling keys has changed significantly with the new release. Many API limitations have been fixed and required behavior
and code changes. The most notable one is that when loading a key there is not distinction between public buffer and
private buffer.

The previous key classes were:

* `io.vertx.ext.auth.KeyStoreOptions` - to work with `jce` keystores
* `io.vertx.ext.auth.SecretOptions` - to handle simmetric secrets
* `io.vertx.ext.auth.PubSecKeyOptions` - to handle pub/sec keys

==== Secrets Management

In Vert.x 4.0 `SecretOptions` is no more, all key configuration is centralized on `PubSecKeyOptions`:

[source,java]
----
// Configure a hashing secret (3.x)
new SecretOptions()
  .setType("HS256")
  .setSecret("password");
----

You Should now use the new API:

[source,java]
----
// Configure a hashing secret (4.0)
new PubSecKeyOptions()
  // algorithms follow the JOSE naming scheme
  .setAlgorithm("HS256")
  .setBuffer("password");
----

==== PubSecKeyOptions Management

Public secret key management was quite opionated on Vert.x 3.x. The configuration object assumed that keys are
configured as key-pairs and that the key data itself is a `PKCS8` encoded string without the standard delimiters.

[source,java]
----
// Configure a key pair (3.x)
new PubSecKeyOptions()
  .setPublicKey(
    // remove the boundaries
    // (don't do this as it doesn't handle end of lines
    // it's for illustration purposes)
    pubPemString
      .replaceAll("-----BEGIN PUBLIC KEY----")
      .replaceAll("-----END PUBLIC KEY----"))
  .setSecretKey(
    // remove the boundaries
    // (don't do this as it doesn't handle end of lines
    // it's for illustration purposes)
    secPemString
      .replaceAll("-----BEGIN PUBLIC KEY----")
      .replaceAll("-----END PUBLIC KEY----"));
----


In Vert.x 4.0 the configuration is **always** about a single key, so a key-pair should be 2 key (the public +
the secret).

[source,java]
----
// Configure a key pair (4.x)
PubSecKeyOptions pubKey =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file (boundaries included)
    .setBuffer(pubPemString);

PubSecKeyOptions secKey =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file (boundaries included)
    .setBuffer(secPemString);
----

This also means that handling `X509` certificates is possible with the same API:

[source,java]
----
// Configure a key pair (4.x)
PubSecKeyOptions x509Certificate =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file (boundaries included)
    .setBuffer(x509PemString);
----

==== KeyStore Management

In Vert.x 3.x `KeyStoreOptions` assumes that the keystore format is `jceks`, and the store password is the same as the
key's password. As `jceks` is a proprietary format, it is advised to use a standard format instead (as modern JDKs also
recommend).

[source,java]
----
// Loading a jceks keystore in 3.x
new KeyStoreOptions()
  .setPath("path/to/keystore.jks")
  .setPassword("keystore-password");
----

In Vert.x 4.0 we assume the default format is the JDK configured default one. This means `PKCS12` in Java 9 and up.

[source,java]
----
// Loading a **jceks** keystore in 4.0
new KeyStoreOptions()
  .setPath("path/to/keystore.jks")
  // this is required as for modern JDKs this isn't the default
  // type and probaly `pkcs12` will be picked instead
  .setType("jceks")
  .setPassword("keystore-password")
  // optionally if your keys have different passwords
  // if a key specific id is not provided it defaults to
  // the keystore password
  .putPasswordProtection("key-id", "key-specific-password");
----
