=== Authentication and Authorization

The Vert.x Auth module has very significant changes in Vert.x 4. The most notable is that the interface
`io.vertx.ext.auth.AuthProvider` is split into 2 newly added interfaces:

1. `io.vertx.ext.auth.authentication.AuthenticationProvider`
2. `io.vertx.ext.auth.authorization.AuthorizationProvider`

This change means that any provider is now able to perform either `authentication` and `authorization` independently.
This of course means that API changes had to be made, and your code may need to be migrated.

==== Migrate Authentication

The authentication mechanism is practically the same, the main change happens at the result level. Before the result
was a `User` object that was provider specific, while in Vert.x 4, it is always a single implementation:
`io.vertx.ext.auth.User`.

[source,java]
----
JsonObject authInfo = new JsonObject()
  .put("username", "john")
  .put("password", "super$ecret");

// Authenticate a user (3.x)
// omitting the error handling for brevity
provider.authenticate(authInfo, res -> {
   if (res.succeeded()) {
     // may require type casting for example on Oauth2
     User user = res.result();
   }
});

// Authenticate a user (4.x)
// omitting the error handling for brevity
provider.authenticate(authInfo, res -> {
   if (res.succeeded()) {
     // Never needs type casting
     User user = res.result();
   }
});
----

==== Migrate Authorization

Authorization is a new feature that you will find on Vert.x 4. Before you could only assert that a `User` was
authorized to perform some task on the `User` object itself (which implies the provider was responsible for both
authentication (authn) and authorization (authz)). Now the `User` is unaware of the provider, so it can be used on
different providers.

As an example, consider an application that checks if a `User` can use `Printer #1234`:

[source,java]
----
// Authorize a user (3.x)
// omitting the error handling for brevity
user.isAuthorized("printers:printer1234", res -> {
  if (res.succeeded()) {
    boolean hasAuthority = res.result();
    if (hasAuthority) {
      System.out.println("User has the authority");
    } else {
      System.out.println("User does not have the authority");
    }
  }
});
----

While this worked fine for `JDBCAuth`, `MongoAuth`, `ShiroAuth`, it did not work for more typical providers such as
`OAuth2` as the provider did not perform authorization checks. This is now possible by mixing the right provider:

[source,java]
----
// Authorize a user (4.x)
// omitting the error handling for brevity
provider.getAuthorizations(user, res -> {
  if (res.succeeded()) {
    if (PermissionBasedAuthorization.create("printer1234").match(user)) {
      System.out.println("User has the authority");
    } else {
      System.out.println("User does not have the authority");
    }
  }
});
----

NOTE: While before the permissions were very basic, the new API allows authorizations on `Roles`,
`Permissions`, `Logic Operations`, `WildCards` and any other implementations you may add.

==== Migrate Providers

Some providers have been deprecated too and replaced by others.

===== Apache Shiro Provider

Apache Shiro provider was a problematic provider for several reasons:

1. It is implemented in a blocking API style, which means that it will not scale as expected for a Vert.x  application
2. It relies on `ThreadLocal` storage which forces the provider to constantly lock and save and restore state, bringing
the overall performance down.

Shiro is used mostly for 2 cases and can be replaced by:

1. `PropertyFile{Authentication|Authorization}` for property file based authentication and authorization
2. `LDAPAuthentication` for LDAP Authentication

===== JDBC Provider

JDBC provider was a problematic provider because it is implemented in a blocking API style, which means that it will
not scale as expected for a Vert.x  application. JDBC auth can be replaced by:

1. `Sql{Authentication|Authorization}` for authn/authz

==== Migrate passwords

In Vert.x 3 providers that relied on managing the user data, would have their own format to store passwords.
In Vert.x 4 this is standardized on https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md[P-H-C].

Vert.x stores passwords securely. You can't just re-encode them in the new format. It is advisably to request the end
user of your application to renew the password during the application migration.

Create a password hash that is compatible with:

* Mongo
* JDBC
* Sql

Takes the following form:

[source,java]
----
// 4.0 only!
String hash = provider.hash(
  "pkdbf2", // hashing algorithm (OWASP recommended)
  VertxContextPRNG.current().nextString(32), // secure random salt
  "super$ecret" // password
);
----

This is quite low level, so in order to simplify your work, some providers have a utility helper that can
create new users:

* JDBCUserUtil
* MongoUserUtil
* SqlUserUtil

These helpers can create the user, roles and permissions directly on the target store, simplifying your work
for migrations.
