=== gRPC

The gRPC support modules have significant changes in Vert.x 4. The most notable change is that in Vert.x 4 the module `protoc-gen-grpc-java` is not present anymore.

This module was a **fork** of the original compiler. This had a few benefits such as producing code that was compatible with the way vert.x works in general, but it had a major dissadvantage, the fork required constant rebases to the upstream and keep up with the releases so we would fix the upstream bugs and keep the generator up to date.

Although this is the most notorious change, this guide does not replace the full detailed list of breaking changes
listed on the https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes#vertx-auth-1[Vert.x WIKI].

==== Migrate build script

As refered before the custom compiler artifact is not present anymore, however there is a official compiler plugin which introduces back the generation of code that is natural to Vert.x. This change means that the existing build scripts need to be updated.

===== Maven builds

If you were using maven as your build tool, this is gist of the required change:

[source,xml]
----
<!-- Vert.x 3.x -->
<plugin>
  <groupId>org.xolstice.maven.plugins</groupId>
  <artifactId>protobuf-maven-plugin</artifactId>
  <configuration>
    <protocArtifact>com.google.protobuf:protoc:3.2.0:exe:${os.detected.classifier}</protocArtifact>
    <pluginId>grpc-java</pluginId>
    <!-- NOTE: the gav coordinates point to the 3.x only compiler fork -->
    <pluginArtifact>io.vertx:protoc-gen-grpc-java:${vertx.grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
  </configuration>
  ...
</plugin>
----

In 4.0 you are supposed to use the **official** compiler and use a plugin to generate the Vert.x specific code:

[source,xml]
----
<!-- Vert.x 4.0 -->
<plugin>
  <groupId>org.xolstice.maven.plugins</groupId>
  <artifactId>protobuf-maven-plugin</artifactId>
  <configuration>
    <protocArtifact>com.google.protobuf:protoc:3.2.0:exe:${os.detected.classifier}</protocArtifact>
    <pluginId>grpc-java</pluginId>
    <!-- NOTE: the gav coordinates point to the official compiler -->
    <pluginArtifact>io.grpc:protoc-gen-grpc-java:${vertx.grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
    <protocPlugins>
      <!-- NEW: a plugin is added to generate the Vert.x specific code -->
      <protocPlugin>
        <id>vertx-grpc-protoc-plugin</id>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-grpc-protoc-plugin</artifactId>
        <version>${vertx.version}</version>
        <mainClass>io.vertx.grpc.protoc.plugin.VertxGrpcGenerator</mainClass>
      </protocPlugin>
    </protocPlugins>
  </configuration>
  ...
</plugin>
----

===== Gradle builds

If you were using gradle as your build tool, this is gist of the required change:

[source,groovy]
----
// Vert.x 4.0.0
...
apply plugin: 'com.google.protobuf'
...
buildscript {
  ...
  dependencies {
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.0'
  }
}
...
protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.2.0'
  }
  plugins {
    // NOTE: the gav is for the forked compiler
    grpc {
      artifact = "io.vertx:protoc-gen-grpc-java:${vertx.grpc.version}"
    }
  }
  generateProtoTasks {
    all()*.plugins {
      grpc
    }
  }
}
----

In 4.0 you are supposed to use the **official** compiler and use a plugin to generate the Vert.x specific code:

[source,groovy]
----
// Vert.x 4.0.0
...
apply plugin: 'com.google.protobuf'
...
buildscript {
  ...
  dependencies {
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.0'
  }
}
...
protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.2.0'
  }
  plugins {
    // NOTE: the gav is for the official compiler
    grpc {
      artifact = "io.grpc:protoc-gen-grpc-java:1.25.0"
    }
    // NOTE: the gav is for the compiler plugin
    vertx {
      artifact = "io.vertx:vertx-grpc-protoc-plugin:${vertx.grpc.version}"
    }
  }
  generateProtoTasks {
    all()*.plugins {
      grpc
      vertx
    }
  }
}
----

==== Generated Code Migration

In vert.x 4 due to the usage of a plugin the Vert.x generated code does not live inside the same source file as before. For example, if you have the following descriptor:

[source,proto]
----
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
----

This would generate the code under the class `GreeterGrpc` in Vert.x 3. However in Vert.x 4.0 the newly generated code will live in `VertxGreeterGrpc`. The reason is that the compiler will not allow custom code generation on it's base class and plugins **must** generate a new class with a different name.

So in your code this would mean:

[source,java]
----
// 3.x
GreeterGrpc.GreeterVertxImplBase service =
  new GreeterGrpc.GreeterVertxImplBase() {
      ...
  }
// 4.x
VertxGreeterGrpc.GreeterVertxImplBase service =
  new VertxGreeterGrpc.GreeterVertxImplBase() {
      ...
  }
----

==== Generated API changes

As it has been noted on other modules, Vert.x 4 is bringing a simpler promise based API so the plugin generates promissified code:


[source,java]
----
// 3.x
GreeterGrpc.GreeterVertxImplBase service =
  new GreeterGrpc.GreeterVertxImplBase() {
        @Override
        public void sayHello(HelloRequest request, Promise<HelloReply> future) {
          future.complete(
              HelloReply.newBuilder().setMessage(request.getName()).build());
        }
  }
// 4.x
VertxGreeterGrpc.GreeterVertxImplBase service =
  new VertxGreeterGrpc.GreeterVertxImplBase() {
      @Override
      public Future<HelloReply> sayHello(HelloRequest request) {
        return Future.succeededFuture(
          HelloReply.newBuilder()
            .setMessage(request.getName())
            .build());
      }
  }
----

This makes it easier to reason about inputs and outputs.
