=== JDBC Client

The Vert.x JDBC Client remains available in Vert.x 4 and will remain supported for the lifetime
of Vert.x 4.

A new reactive SQL client has been designed for the past 2 years built on top of the experience we learned
from the Vert.x JDBC Client feedback from the community.

The new SQL client API has a few implementations:

- a reactive PostgreSQL client (formerly the Reactive PG Client)
- a reactive MySQL client
- a reactive DB2 client
- the current JDBC client (offering the former JDBC client API and the SQL client API)

The reactive implementations use the database network protocols and are resource-efficient, while the JDBC client uses worker threads to deal with the blocking nature of JDBC.


==== Creating Pool

Creating a pool (in 3.x there was no concept of pool, it was called a client). Creating such object is as simple as:

[source,java]
----
// 3.x
SQLClient client = JDBCClient.create(vertx, jsonConfig);

// 4.x
JDBCPool pool = JDBCPool.pool(vertx, jsonConfig);
----

NOTE: Using the 3.x API is still valid but the recommended way to develop in 4.x is to use the new API.

The `jsonConfig` has several benefits and limitations. While you can pretty much configure anything it can
be error prone. For this reason the new API introduces a type safe config too:

[source,java]
----
// 4.x ONLY!!!
JDBCPool pool = JDBCPool.pool(
      vertx,
      // configure the connection
      new JDBCConnectOptions()
        // H2 connection string
        .setJdbcUrl("jdbc:h2:~/test")
        // username
        .setUser("sa")
        // password
        .setPassword(""),
      // configure the pool
      new PoolOptions()
        .setMaxSize(16)
    );
----

NOTE: The type safe config requires `agroal` connection pool to be used as it does not expose many configuration options
making it simple to use.

A pool allows you to perform simple queries without worrying about the connection management. This is useful for single
queries. For complex queries or multiple queries, a connection should be managed by the user:

[source,java]
----
// 3.x
client.getConnection(res -> {
  if (res.succeeded()) {
    SQLConnection connection = res.result();
    // very important! don't forget to return the connection
    connection.close();
  } else {
    // Failed to get connection - deal with it
  }
});

// 4.x
pool
  .getConnection()
  .onFailure(e -> {
    // failed to get a connection
  })
  .onSuccess(conn -> {
    // very important! don't forget to return the connection
    conn.close();
  });
----

==== Running Queries

===== One Shot

Running queries without managing the connection can be done as:

[source,java]
----
// 3.x
client.query("SELECT * FROM user WHERE emp_id > ?", new JsonArray().add(1000), res -> {
  if (res.succeeded()) {
    ResultSet rs = res2.result();
    // Do something with results
  }
});

// 4.x
pool
  .preparedQuery("SELECT * FROM user WHERE emp_id > ?")
  // the emp id to look up
  .execute(Tuple.of(1000))
  .onSuccess(rows -> {
    for (Row row : rows) {
      System.out.println(row.getString("FIRST_NAME"));
    }
  });
----

===== Running Queries on manually managed connections

This is a mix of the previous cases:

[source,java]
----
pool
  .getConnection()
  .onFailure(e -> {
    // failed to get a connection
  })
  .onSuccess(conn -> {
    conn
      .query("SELECT * FROM user")
      .execute()
      .onFailure(e -> {
        // handle the failure

        // very important! don't forget to return the connection
        conn.close();
      })
      .onSuccess(rows -> {
        for (Row row : rows) {
          System.out.println(row.getString("FIRST_NAME"));
        }
        // very important! don't forget to return the connection
        conn.close();
      });
  });
----

==== Stored Procedures

Stored procedures are also supported in the new client, passing arguments `IN` can be done as:

[source,java]
----
// 3.x
connection.callWithParams(
  "{ call new_customer(?, ?) }",
  new JsonArray().add("John").add("Doe"),
  null,
  res -> {
    if (res.succeeded()) {
      // Success!
    } else {
      // Failed!
    }
  });

// 4.0
client
  .preparedQuery("{call new_customer(?, ?)}")
  .execute(Tuple.of("Paulo", "Lopes"))
  .onSuccess(rows -> {
    ...
  });
----

This was already supported in 3.x however mixing `IN` and `OUT` arguments was very limited in term of
types. The new pool is type safe so it can cover pretty much any type JDBC can handle:

[source,java]
----
// 3.x
connection.callWithParams(
  "{ call customer_lastname(?, ?) }",
  new JsonArray().add("John"),
  new JsonArray().addNull().add("VARCHAR"),
  res -> {
    if (res.succeeded()) {
      ResultSet result = res.result();
    } else {
      // Failed!
    }
});

// 4.x
client
  .preparedQuery("{call customer_lastname(?, ?)}")
  .execute(Tuple.of("John", SqlOutParam.OUT(JDBCType.VARCHAR)))
  .onSuccess(rows -> {
    ...
  });
----

It is important to note that if a argument is of type `OUT` it is now possible to specify it's return type.
In this specific case we specify `VARCHAR` using the JDBC specific constant.

The new API has the advantage that the types are not bound to the limitations of JSON. It also means you can
use database specific types instead of relying on text constants for the type name.

NOTE: For more complex scenarios the new API allows `INOUT` parameters too.

