=== Vert.x Web and OpenAPI

==== New module

Vert.x 4 provides a new module in order to develop Contract-Driven applications using `vertx-web` and OpenAPI: `vertx-web-openapi`.
In order to simplify the transitioning to the new module, we'll continue to publish `vertx-web-api-contract` over the Vert.x 4 lifecycle, but we strongly suggest our users to switch soon to `vertx-web-openapi`.

Although the validation logic was completely rewritten from scratch, the new module behaves similarly to the previous one, but the API surface was reworked in order to make it simpler to use and consistent with Vert.x Web `Router`.
The new module has only Vert.x dependencies, including the new https://vertx-web-site.github.io/docs/vertx-json-schema/java/[`vertx-json-schema`] and https://vertx-web-site.github.io/docs/vertx-web-validation/java/[`vertx-web-validation`].

The new module main package is `io.vertx.ext.web.openapi`.

==== `OpenAPI3RouterFactory` becomes `RouterFactory`

Similarly to the old module, in `vertx-web-openapi` you start instantiating the `RouterFactory`:

```java
RouterFactory.create(vertx, "petstore.yaml").onComplete(ar -> {
  if (ar.succeeded()) {
    // Spec loaded with success
    RouterFactory routerFactory = ar.result();
  } else {
    // Something went wrong during router factory initialization
    Throwable exception = ar.cause();
  }
});
```

Or even better, using the new methods in Vert.x Futures:

```java
RouterFactory.create(vertx, "petstore.yaml")
  .onSuccess(routerFactory -> {
    // Spec loaded with success
  })
  .onFailure(exception -> {
    // Something went wrong during router factory initialization
  });
```

Because in the new module we use the Vert.x Filesystem APIs to load the files, you don't need to specify the `/` for the classpath resources.
`"petstore.yaml"` is enough to let the `RouterFactory` pick the contract from your classpath resources.

In most use cases, you can simply search and replace usages of old `OpenAPI3RouterFactory` with the new methods from `RouterFactory`, for example:

.RouterFactory
|===
|Old `OpenAPI3RouterFactory` |New `RouterFactory`

|`routerFactory.addHandlerByOperationId("getPets", handler)`
|`routerFactory.operation("getPets").handler(handler)`

|`routerFactory.addFailureHandlerByOperationId("getPets", handler)`
|`routerFactory.operation("getPets").failureHandler(handler)`

|`routerFactory.mountOperationToEventBus("getPets", "getpets.myapplication")`
|`routerFactory.operation("getPets").routeToEventBus("getpets.myapplication")`

|`routerFactory.addGlobalHandler(handler)`
|`routerFactory.rootHandler(handler)`

|`routerFactory.addBodyHandler(handler)`
|`routerFactory.bodyHandler(handler)`

|`routerFactory.getRouter()`
|`routerFactory.createRouter()`
|===

To access to the parsed request parameters:

```java
RequestParameters parameters = routingContext.get(io.vertx.ext.web.validation.ValidationHandler.REQUEST_CONTEXT_KEY);
int aParam = parameters.queryParameter("aParam").getInteger();
```

==== Security handlers

Following the ./auth.adoc[AuthN/Z changes in Vert.x Web], now the methods `addSecurityHandler` and `addSecuritySchemaScopeValidator` don't exist anymore.
They're replaced with a single method, called `RouterFactory#securityHandler`, that accepts `io.vertx.ext.web.handler.AuthenticationHandler` as handlers and can automatically recognize `OAuth2Handler` in order to properly setup security schema scopes.

The new security handlers also properly implements the and/or chain, as described by the OpenAPI spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#operationObject

=== Common failures handlers

The methods to setup the validation failure handler and the not implemented failure handler were removed, now you can just setup these handlers in the `Router` generated by the `RouterFactory` using `Router#errorHandler(int, Handler)`:

.RouterFactory
|===
|`vertx-web-api-contract` | `vertx-web-openapi`

|`routerFactory.setValidationFailureHandler(handler)`
|`router.errorHandler(400, handler)`

|`routerFactory.setNotImplementedFailureHandler(handler)`
|`router.errorHandler(501, handler)`
|===

==== Accessing the OpenAPI contract model

We don't map the OpenAPI contract anymore to POJOs, so we don't bring in the additional swagger-parser dependency.
But we provide getters and resolvers to retrieve specific components of the contract, starting from the single operation:

```java
JsonObject model = routerFactory.operation("getPets").getOperationModel();
```

To the whole contract itself:

```java
JsonObject contract = routerFactory.getOpenAPI().getOpenAPI();
```

We also expose the functionality to resolve particular pieces of the contract:

```java
JsonObject petModel = routerFactory.getOpenAPI().getCached(JsonPointer.from("/components/schemas/Pet"));
```

==== Validating Web Requests without OpenAPI

In `vertx-web-api-contract` we used to expose the validation logic, without the need of OpenAPI, using `HTTPRequestValidationHandler`.
In Vert.x 4, the validation logic is encapsulated in another module, called `vertx-web-validation`, that you can import and use without OpenAPI.

The new entrypoint for this module is called `ValidationHandler` and It provides a completely different API from `HTTPRequestValidationHandler`.
We encourage you to look at the documentation for more details: https://vertx-web-site.github.io/docs/vertx-web-validation/java/

==== Vert.x Web API Service

The `vertx-web-api-service` module was internally refactored to adapt it to `vertx-web-validation`.
For OpenAPI users that will use `vertx-web-openapi`, the usage of this module doesn't change.

On the other hand, if you're not an OpenAPI user, you can use this module using `vertx-web-validation` alone with the class `RouteToEBServiceHandler`:

```java
router.get("/api/transactions")
  .handler(
    ValidationHandlerBuilder.create(schemaParser)
      .queryParameter(optionalParam("from", stringSchema()))
      .queryParameter(optionalParam("to", stringSchema()))
      .build()
  ).handler(
    RouteToEBServiceHandler.build(eventBus, "transactions.myapplication", "getTransactionsList")
  );
```

We encourage you to look at the documentation for more details: https://vertx-web-site.github.io/docs/vertx-web-api-service/java/

This module is not compatible anymore with `vertx-web-api-contract` so, if you're going to upgrade to Vert.x 4, please migrate your Vert.x OpenAPI code to `vertx-web-openapi`.
