== Overview

Vert.x 4 builds on the foundation laid by Vert.x 3 and brings a few significant improvements brought by the
feedback of its community.

If you are acquainted with Vert.x 3, you are almost ready to write a Vert.x 4 application.

This overview explains the key changes between the two versions in order to facilitate the migration of a Vert.x 3
application to Vert.x 4.

=== Callback to the future

Vert.x 3 programming model uses extensively callbacks for asynchronous operations

```java
HttpRequest request = client.get("/resource");

request.send(ar -> {
  if (ar.succeeded()) {
    HttpResponse response = ar.result();
  } else {
    Throwable error = ar.cause();
  }
});
```

Vert.x 4 extends this model with futures: you can still use callbacks for asynchronous operations, but now you have instead
the opportunity to use a future-ized version of the method

```java
HttpRequest request = client.get("/resource");

Future<HttpResponse> response = request.send();

response.onComplete(ar -> {
  if (ar.succeeded()) {
    HttpResponse response = ar.result();
  } else {
    Throwable failure = ar.cause();
  }
});
```

There are various reasons behing this callback/future hybrid model design, the most important one being that it eases
the migration of callback based applications to Vert.x 4 . Later these applications can be migrated to futures.

For simple operations you won't see much of a difference between callback and futures (since you ultimately need a callback
to process the future result), however futures become very handy for composing asynchronous operations.

Here is a callback example that composes two asynchronous operations:

```java
client.get("/resource1").send(ar1 -> {
  if (ar1.succeeded()) {
    HttpResponse response = ar.result();
    JsonObject json = response.body();
    client.put("/resource2").sendJsonObject(ar2 -> {
      if (ar2.succeeded()) {
        // Handle final result
      } else {
        Throwable failure2 = ar.cause();
      }
    });
  } else {
    Throwable failure1 = ar.cause();
  }
});
```

Here is the same example using future composition instead

```java
Future<HttpResponse> fut1 = client.get("/resource1").send();

Future<HttpResponse> fut2 = fut1.compose(response -> client.put("/resource2").sendJsonObject(response.body()));

fut2.onComplete(ar -> {
  if (ar.succeeded()) {
    // Handle final result
  } else {
    Throwable failure = ar.cause();
  }
});
```

One of the major improvements is error handling, callbacks needs to handle failures are every stage
of the composition whereas the futures usually handle the failure once.

=== Deprecate me I'm famous

Like any other piece of software Vert.x 4 improves existing API offered by Vert.x 3. Some of them changes
can lead to API deprecations.

Deprecated APIs follow these following principles

1. The API is deprecated in Vert.x 3 and a new equivalent API is provided
2. The API is removed in Vert.x 4

If your code is using a deprecated Vert.x 3 API, you should update your code to use the equivalent replacement.

Here is a simple example with the Event Bus

```java
// Send is deprecated in Vert.x 3
vertx.eventBus().send("some-address", "hello world", ar -> {
  // Handle response here
});
```

The method `send(String,String,Handler<AsyncResult<Message>>)` is replaced in Vert.x 4 by `request(String,String,Handler<AsyncResult<Message>>)`

```java
// Works with Vert.x 3 and Vert.x 4
vertx.eventBus().request("some-address", "hello world", ar -> {
  // Handle response here
});
```

When you plan to migrate your application, one part of your migration plan is to remove the usage of deprecated APIs.

The Java compiler is configured by default for reporting deprecated API usage and can be very handy for this.

=== Json changes

- Jackson databind not present anymore by default
- ...

=== Component stack changes (?)

