[id="changes-in-infinispan-cluster-manager_{context}"]
= Changes in Infinispan cluster manager

The following section describes the changes in the Infinispan cluster manager.

== Updates in custom configurations

The Infinispan cluster manager is based on Infinispan 11.

In {VertX} {4}, the clustering SPI has been redesigned. The subscription data model has changed. As a result of this, {VertX} {3x} nodes and {VertX} {4} nodes cannot be added together in the same Infinispan cluster manager.

The {VertX} applications are not impacted by this change as the EventBus and SharedData APIs remain the same.

If you have the custom configurations from Vertx. 3.x, update the following parameters in the configuration file in {VertX} {4}:

* Change the `__vertx.subs` cache type to replicated instead of distributed.
* Add the replicated cache `__vertx.nodeInfo`.

----
 <cache-container default-cache="distributed-cache">
    <distributed-cache name="distributed-cache"/>
    <replicated-cache name="__vertx.subs"/>
    <replicated-cache name="__vertx.haInfo"/>
    <replicated-cache name="__vertx.nodeInfo"/>
    <distributed-cache-configuration name="__vertx.distributed.cache.configuration"/>
  </cache-container>
----
