[id="changes-in-vertx-service-discovery_{context}"]
= Changes in {VertX} service discovery

The following section describes the changes in {VertX} service discovery.

== Removed create methods from service discovery that contain `ServiceDiscovery` argument 

The following create methods in service discovery that have `Handler<ServiceDiscovery>` as an argument have been removed. These methods cannot be used with futures.

[options="header"]
|===
|Removed methods|Replacing methods
|`ServiceDiscovery.create(..., Handler<ServiceDiscovery> completionHandler)`|`ServiceDiscovery.create(Vertx)`
|`ServiceDiscovery.create(..., Handler<ServiceDiscovery> completionHandler)`|`ServiceDiscovery.create(Vertx, ServiceDiscoveryOptions)`
|===

== Service importer and exporter methods are no longer fluent

The `ServiceDiscovery.registerServiceImporter()` and `ServiceDiscovery.registerServiceExporter()` methods are no longer fluent. The methods return `Future<Void>`.


== Kubernetes Service Importer no longer registered automatically

Since {VertX} {v4}, the Kubernetes bridge is no longer registered automatically.
It is not sufficient anymore to have it on the _classpath_.

It must be registered manually after creating `ServiceDiscovery`:

[source,java,options="nowrap",subs="attributes+"]
----
JsonObject defaultConf = new JsonObject();
serviceDiscovery.registerServiceImporter(new KubernetesServiceImporter(), defaultConf);
----


