[id="changes-in-vertx-service-discovery_{context}"]
= Changes in {VertX} service discovery

The following section describes the changes in {VertX} service discovery.

== Removed create methods from service discovery that contain `ServiceDiscovery` argument 

The following create methods in service discovery that have `Handler<ServiceDiscovery>` as an argument have been removed. These methods cannot be used with futures.

[options="header"]
|===
|Removed methods|Replacing methods
|`ServiceDiscovery.create(..., Handler<ServiceDiscovery> completionHandler)`|`ServiceDiscovery.create(Vertx)`
|`ServiceDiscovery.create(..., Handler<ServiceDiscovery> completionHandler)`|`ServiceDiscovery.create(Vertx, ServiceDiscoveryOptions)`
|===

== Service importer and exporter methods are no longer fluent

The `ServiceDiscovery.registerServiceImporter()` and `ServiceDiscovery.registerServiceExporter()` methods are no longer fluent. The methods return `Future<Void>`.


== Kubernetes service importer is no longer registered automatically

The `vertx-service-discovery-bridge-kubernetes` adds the `KubernetesServiceImporter` discovery bridge.
The bridge imports services from Kubernetes or Openshift into the Eclipse Vert.x service discovery.

From {VertX} {v4}, this bridge is no longer registered automatically.
Even if you have added the bridge in the classpath of your project, it will not be automatically registered.

You must manually register the bridge after creating the `ServiceDiscovery` instance.

The following example shows you how to manually register the bridge.

[source,java,options="nowrap",subs="attributes+"]
----
JsonObject defaultConf = new JsonObject();
serviceDiscovery.registerServiceImporter(new KubernetesServiceImporter(), defaultConf);
----
