[id="con_mg_generic-updates-in-vertx-http_{context}"]
= Generic updates in {VertX} HTTP methods

The following section describes the miscellaneous updates in {VertX} HTTP methods.

== Updates in HTTP Methods for `WebSocket`

The changes in `WebSocket` are:

* The usage of the term `WebSocket` in method names was inconsistent. The method names had incorrect capitalization, for example, `Websocket`, instead of `WebSocket`. The methods that had inconsistent usage of `WebSocket` in the following classes have been removed. Use the new methods that have correct capitalization instead.

** The following methods in `HttpServerOptions` class have been removed.
+
[options="header"]
|===
|Removed methods|New methods
|`getMaxWebsocketFrameSize()`|`getMaxWebSocketFrameSize()`
|`setMaxWebsocketFrameSize()`|`setMaxWebSocketFrameSize()`
|`getMaxWebsocketMessageSize()`|`getMaxWebSocketMessageSize()`
|`setMaxWebsocketMessageSize()`|`setMaxWebSocketMessageSize()`
|`getPerFrameWebsocketCompressionSupported()`|`getPerFrameWebSocketCompressionSupported()`
|`setPerFrameWebsocketCompressionSupported()`|`setPerFrameWebSocketCompressionSupported()`
|`getPerMessageWebsocketCompressionSupported()`|`getPerMessageWebSocketCompressionSupported()`
|`setPerMessageWebsocketCompressionSupported()`|`setPerMessageWebSocketCompressionSupported()`
|`getWebsocketAllowServerNoContext()`|`getWebSocketAllowServerNoContext()`
|`setWebsocketAllowServerNoContext()`|`setWebSocketAllowServerNoContext()`
|`getWebsocketCompressionLevel()`|`getWebSocketCompressionLevel()`
|`setWebsocketCompressionLevel()`|`setWebSocketCompressionLevel()`
|`getWebsocketPreferredClientNoContext()`|`getWebSocketPreferredClientNoContext()`
|`setWebsocketPreferredClientNoContext()`|`setWebSocketPreferredClientNoContext()`
|`getWebsocketSubProtocols()`|`getWebSocketSubProtocols()`
|`setWebsocketSubProtocols()`|`setWebSocketSubProtocols()`
|===
+
The new methods for `WebSocket` subprotocols use `List<String>` data type instead of a comma separated string to store items.

** The following methods in `HttpClientOptions` class have been removed.
+
[options="header"]
|===
|Removed Methods|Replacing Methods
|`getTryUsePerMessageWebsocketCompression()`|`getTryUsePerMessageWebSocketCompression()`
|`setTryUsePerMessageWebsocketCompression()`|`setTryUsePerMessageWebSocketCompression()`
|`getTryWebsocketDeflateFrameCompression()`|`getTryWebSocketDeflateFrameCompression()`
|`getWebsocketCompressionAllowClientNoContext()`|`getWebSocketCompressionAllowClientNoContext()`
|`setWebsocketCompressionAllowClientNoContext()`|`setWebSocketCompressionAllowClientNoContext()`
|`getWebsocketCompressionLevel()`|`getWebSocketCompressionLevel()`
|`setWebsocketCompressionLevel()`|`setWebSocketCompressionLevel()`
|`getWebsocketCompressionRequestServerNoContext()`|`getWebSocketCompressionRequestServerNoContext()`
|`setWebsocketCompressionRequestServerNoContext()`|`setWebSocketCompressionRequestServerNoContext()`
|===

** The following handler methods in `HttpServer` class have been removed.
+
[options="header"]
|===
|Deprecated Methods|New Methods
|`websocketHandler()`|`webSocketHandler()`
|`websocketStream()`|`webSocketStream()`
|===

* `WebsocketRejectedException` is deprecated. The methods throw `UpgradeRejectedException` instead.

* The `HttpClient` `webSocket()` methods use  `Handler<AsyncResult<WebSocket>>` instead of `Handler` or `Handler<Throwable>`.

* The number of overloaded methods to connect an HTTP client to a WebSocket has also been reduced by using the methods in `WebSocketConnectOptions` class.

* The `HttpServerRequest.upgrade()` method has been removed. This method was synchronous.
+
Use the new method `HttpServerRequest.toWebSocket()` instead. This new method is asynchronous.
+
The following example shows the use of synchronous method in {VertX} {v3x}.
+
----
// 3.x
server.requestHandler(req -> {
  WebSocket ws = req.upgrade();
});
----
+
The following example shows the use of asynchronous method in {VertX} {v4}.
+
----
// 4.0
server.requestHandler(req -> {
  Future<WebSocket> fut = req.toWebSocket();
  fut.onSuccess(ws -> {
  });
});
----

== Setting the number of WebSocket connections

In {VertX} {v3x}, you could use the the HTTP client pool size to define the maximum number of WebSocket connections in an application. The value accessor methods `HttpClientOptions.maxPoolSize()` were used to get and set the WebSocket connections. The default number of connections was set to 4 for each endpoint.

The following example shows how WebSocket connections are set in {VertX} {v3x}.

----
// 3.x
options.setMaxPoolSize(30); // Maximum connection is set to 30 for each endpoint
----

However, in {VertX} {v4}, there is no pooling of WebSocket TCP connections, because the connections are closed after use. The applications use a different pool for HTTP requests. Use the value accessor methods `HttpClientOptions.maxWebSockets()` to get and set the WebSocket connections. The default number of connections is set to 50 for each endpoint.

The following example shows how to set WebSocket connections in {VertX} {v4}.

----
// 4.0
options.setMaxWebSockets(30); // Maximum connection is set to 30 for each endpoint
----

== `HttpMethod` is available as a interface

`HttpMethod` is available as a new interface.

In earlier releases of {VertX}, `HttpMethod` was declared as an enumerated data type. As an enumeration, it limited the extensibility of HTTP. Further, it prevented serving other HTTP methods with this type directly. You had to use the  `HttpMethod.OTHER` value along with the `rawMethod` attribute during server and client HTTP requests.

If you are using `HttpMethod` enumerated data type in a switch block, you can use the following code to migrate your applications to {VertX} {v4}.

The following example shows a switch block in {VertX} {v3x} releases.

[source,java,options='nowrap',subs=`attributes`]
----
switch (method) {
  case GET:
    ...
    break;
  case OTHER:
    String s = request.getRawMethod();
    if (s.equals("PROPFIND") {
      ...
    } else ...
}
----

The following example shows a switch block in {VertX} {v4}.

[source,java,options='nowrap',subs=`attributes`]
----
switch (method.name()) {
  case "GET":
    ...
    break;
  case "PROPFIND";
    ...
    break;
}
----

You can also use the following code in {VertX} {v4}.

----
HttpMethod PROPFIND = HttpMethod.valueOf("PROPFIND");

if (method == HttpMethod.GET) {
  ...
} else if (method.equals(PROPFIND)) {
  ...
} else {
  ...
}
----

If you are using `HttpMethod.OTHER` value in your applications, use the following code to migrate the application to {VertX} {v4}.

The following example shows you the code in {VertX} {v3x} releases.
----
client.request(HttpMethod.OTHER, ...).setRawName("PROPFIND");
----

The following example shows you the code in {VertX} {v4}.
----
client.request(HttpMethod.valueOf("PROPFIND"), ...);
----
