[id="changes-in-infinispan-cluster-manager_{context}"]
= Changes in Infinispan cluster manager

The following section describes the changes in the Infinispan cluster manager.

== Updates in custom configurations

The Infinispan cluster manager is based on Infinispan 11.

In {VertX} {v4}, the clustering SPI has been redesigned. The subscription data model has changed. As a result of this, {VertX} {v3x} nodes and {VertX} {v4} nodes cannot be added together in the same Infinispan cluster.

The {VertX} applications are not impacted by this change as the EventBus and SharedData APIs remain the same.

If you had a custom Infinispan configuration file in your {VertX} {v3x} application:

* Change the `__vertx.subs` cache type to replicated instead of distributed.
* Add the replicated cache `__vertx.nodeInfo`.

----
 <cache-container default-cache="distributed-cache">
    <distributed-cache name="distributed-cache"/>
    <replicated-cache name="__vertx.subs"/>
    <replicated-cache name="__vertx.haInfo"/>
    <replicated-cache name="__vertx.nodeInfo"/>
    <distributed-cache-configuration name="__vertx.distributed.cache.configuration"/>
  </cache-container>
----

If you run an {VertX} cluster on Openshift, the `infinispan-cloud` JAR is no longer needed. The JAR has been removed from the dependencies section of the build file. The configuration files that were bundled in this JAR are now included in the `infinispan-core` JAR.
