[id="changes-in-key-management_{context}"]
= Changes in key management

In {VertX} {v4}, there are major updates in handling keys. The most important change is that when a key loads, there is no distinction between public buffer and private buffer.

The following classes have been updated:

* `io.vertx.ext.auth.KeyStoreOptions` used to work with `jce` keystores

* `io.vertx.ext.auth.SecretOptions` used to handle symmetric secrets

* `io.vertx.ext.auth.PubSecKeyOptions` used to handle public secret keys

The following section describes the changes in key management.

== Secret options class is no longer available

The `SecretOptions` class is no longer available. Use the new `PubSecKeyOptions` class instead to work with a cryptographic key.

The following example shows how methods of `SecretOptions` class were used in {VertX} {v3x} releases.

[source,java,options="nowrap",subs="attributes+"]
----
new SecretOptions()
    .setType("HS256")
    .setSecret("password")
----

The following example shows how methods of `PubSecKeyOptions` class should be used in {VertX} {v4}.

[source,java,options="nowrap",subs="attributes+"]
----
new PubSecKeyOptions()
    .setAlgorithm("HS256")
    .setSecretKey("password")
----

== Updates in public secret keys management

In {VertX} {v3x}, the configuration object in public secret key management assumed that:

* Keys are configured as key-pairs.
* Key data is a PKCS8 encoded string without standard delimiters.

The following example shows how to configure key pair in {VertX} {v3x}.

[source,java,options="nowrap",subs="attributes+"]
----
new PubSecKeyOptions()
  .setPublicKey(
    // remove the PEM boundaries
    pubPemString
      .replaceAll("-----BEGIN PUBLIC KEY----")
      .replaceAll("-----END PUBLIC KEY----"))
  .setSecretKey(
    // remove the PEM boundaries
    secPemString
      .replaceAll("-----BEGIN PUBLIC KEY----")
      .replaceAll("-----END PUBLIC KEY----"));
----

In {VertX} {v4}, you must specify both the public and private key.

The following example shows how to configure key pair in {VertX} {v4}.

[source,java,options="nowrap",subs="attributes+"]
----
PubSecKeyOptions pubKey =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file and had boundaries included in it
    .setBuffer(pubPemString);

PubSecKeyOptions secKey =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file and had boundaries included in it
    .setBuffer(secPemString);
----

You can now handle X509 certificates using `PubSecKeyOptions`.

[source,java,options="nowrap",subs="attributes+"]
----
PubSecKeyOptions x509Certificate =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file and had boundaries included in it
    .setBuffer(x509PemString);
----

== Changes in keystore management

In {VertX} {v3x}, `KeyStoreOptions` assumes that the keystore format is `jceks`, and the stored password is the same as the password of the key. As `jceks` is a proprietary format, it is recommended to use a standard format, such as JDK, instead.

When you use `KeyStoreOptions` in {VertX} {v4}, you can specify a store type. For example, store types such as PKCS11, PKCS12, and so on can be set. The default store type is `jceks`.

In {VertX} {v3x}, all keystore entries would share the same password, that is, the keystore password. In {VertX} {v4}, each keystore entry can have a dedicated password. If you do not want to set password for each keystore entry, you can configure the keystore password as the default password for all entries.

The following example shows how to load a `jceks` keystore in {VertX} {v3x}.

[source,java,options="nowrap",subs="attributes+"]
----
new KeyStoreOptions()
  .setPath("path/to/keystore.jks")
  .setPassword("keystore-password");
----

In {VertX} {v4}, the default format is assumed to be the default format configured by JDK. The format is `PKCS12` in Java 9 and above.

The following example shows how to load a `jceks` keystore in {VertX} {v4}.

[source,java,options="nowrap",subs="attributes+"]
----
new KeyStoreOptions()
  .setPath("path/to/keystore.jks")
  // Modern JDKs use `jceks` keystore. But this type is not the default
  // If the type is not set to `jceks` then probably `pkcs12` will be used
  .setType("jceks")
  .setPassword("keystore-password")
  // optionally if your keys have different passwords
  // and if a key specific id is not provided it defaults to
  // the keystore password
  .putPasswordProtection("key-id", "key-specific-password");
----
