[id="changes-in-handlers_{context}"]
= Changes in future

This section explains the changes in future.

== Support for multiple handlers for futures

From {VertX} {v4} onward, multiple handlers are supported for a future. The `Future<T>.setHandler()` method used to set a single handler and has been removed. Use `Future<T>.onComplete()`, `Future<T>.onSuccess()`, and `Future<T>.onFailure()` methods instead to call handlers on completion, success, and failure results of an action.

The following example shows how to call a handler in {VertX} {v3x} releases.
----
Future<String> fut = getSomeFuture();
fut.setHandler(ar -> ...);
----

The following example shows how to call the new `Future<T>.onComplete()` method in {VertX} {v4}.

----
Future<String> fut = getSomeFuture();
fut.onComplete(ar -> ...);
----

== Removed the `completer()` method in future

In earlier releases of {VertX}, you would use the `Future.completer()` method to access `Handler<AsyncResult<T>>`, which was associated with the `Future`.

In {VertX} {v4}, the `Future<T>.completer()` method has been removed. `Future<T>` directly extends `Handler<AsyncResult<T>>`. You can access all the handler methods using the `Future` object. The `Future` object is also a handler.

== Removed the connection handler method in HTTP client request

The `HttpClientRequest.connectionHandler()` method has been removed. Use `HttpClient.connectionHandler()` method instead to call connection handlers for client requests in your application.

The following example shows how the `HttpClientRequest.connectionHandler()` method was used in {VertX} {v3x} releases.
----
client.request().connectionHandler(conn -> {
  // Connection related code
}).end();
----

The following example shows you how to use the new `HttpClient.connectionHandler()` method in {VertX} {v4}.
----
client.connectionHandler(conn -> {
  // Connection related code
});
----
