[id="changes-in-vertx-web-graphql_{context}"]
= Changes in {VertX} Web GraphQL

The following section describes the changes in {VertX} Web GraphQL.

== Updated methods to be supported on multi-language (polyglot) environments

The following methods have been updated and are now supported on polyglot environments:
* `UploadScalar` is now a factory, use the method  `UploadScalar.create()` instead.

* `VertxBatchLoader` is now a factory, use the method `io.vertx.ext.web.handler.graphql.dataloader.VertxBatchLoader.create()` instead.

* `VertxDataFetcher` is now a factory, use the method `io.vertx.ext.web.handler.graphql.schema.VertxDataFetcher.create()` instead.

* `VertxPropertyDataFetcher` is now a factory, use the method  `io.vertx.ext.web.handler.graphql.schema.VertxPropertyDataFetcher.create()` instead.

== Handling POST requests in {VertX} Web GraphQL

In prior releases, the {VertX} Web GraphQL handler could process its own POST requests. It did not need {VertX} Web `BodyHandler` to process the requests. However, this implementation was susceptible to DDoS attacks.

From {VertX} {v4} onward, to process POST requests `BodyHandler` is required. You must install `BodyHandler` before installing {VertX} Web GraphQL handler.
