[id="changes-in-vertx-mqtt_{context}"]
= Changes in {VertX} MQTT

The following section describes the changes in {VertX} MQTT.

== Some fluent methods in MQTT clients return future

Some fluent methods in `MqttClient` class return `Future` instead of being fluent. For example, methods such as, `MqttClient.connect()`, `MqttClient.disconnect()`, `MqttClient.publish()` return future in {VertX} {v4}.

The following example shows the use of `publish()` method in {VertX} {v3x} releases.

[source,java,options="nowrap",subs="attributes+"]
----
client
   .publish("hello", Buffer.buffer("hello"), MqttQoS.EXACTLY_ONCE, false, false)
   .publish("hello", Buffer.buffer("hello"), MqttQoS.AT_LEAST_ONCE, false, false);
----

The following example shows the use of `publish()` method in {VertX} {v4} release.

[source,java,options="nowrap",subs="attributes+"]
----
client.publish("hello", Buffer.buffer("hello"), MqttQoS.EXACTLY_ONCE, false, false);
client.publish("hello", Buffer.buffer("hello"), MqttQoS.AT_LEAST_ONCE, false, false);
----

== `MqttWill` messages return buffer

The `MqttWill` data object wraps a string message as an {VertX} buffer instead of a byte array.

== Removed the deprecated `MqttWill` and authorization methods from MQTT

The following MQTT methods have been removed:

|===
|Removed methods|Replacing methods
|`MqttWill.willMessage()`| `MqttWill.getWillMessage()`
|`MqttWill.willTopic()`|`MqttWill.getWillTopic()`
|`MqttWill.willQos()`|`MqttWill.getWillQos()`
|`MqttAuth.username()`|`MqttAuth.getUsername()`
|`MqttAuth.password()`|`MqttAuth.getPassword()`
|`MqttClientOptions.setKeepAliveTimeSeconds()`|`MqttClientOptions.setKeepAliveInterval()`
|===
