[id="changes-in-json_{context}"]
= Changes in JSON

This section describes changes in JSON.

== Encapsulation of Jackson

All the methods in the JSON class that implement Jackson types have been removed. Use the following methods instead:

[options="header"]
|===
|Removed Fields/Methods|New methods
|`Json.mapper()` field|`DatabindCodec.mapper()`
|`Json.prettyMapper()` field|`DatabindCodec.prettyMapper()`
|`Json.decodeValue(Buffer, TypeReference<T>)`|`JacksonCodec.decodeValue(Buffer, TypeReference)`
|`Json.decodeValue(String, TypeReference<T>)`|
`JacksonCodec.decodeValue(String, TypeReference)`
|===

For example, use the following code:

* When using Jackson `TypeReference`:
** In {VertX} {3x} releases:
+
----
List<Foo> foo1 = Json.decodeValue(json, new TypeReference<List<Foo>>() {});
----

** In {VertX} {4} release:
+
----
List<Foo> foo2 = io.vertx.core.json.jackson.JacksonCodec.decodeValue(json, new TypeReference<List<Foo>>() {});
----

* Referencing an `ObjectMapper`:

** In {VertX} {3x} releases:
+
----
ObjectMapper mapper = Json.mapper;
----

** In {VertX} {4} release:
+
----
mapper = io.vertx.core.json.jackson.DatabindCodec.mapper();
----

* Setting an `ObjectMapper`:

** In {VertX} {3x} releases:
+
----
Json.mapper = someMapper;
----

** From {VertX} {4} onward, you cannot write a mapper instance. You should use your own static mapper or configure the `Databind.mapper()` instance.

== Base64 encoder updated to Base64URL for JSON objects and arrays

The {VertX} JSON types implement RFC-7493. In earlier releases of {VertX}, the implementation incorrectly used Base64 encoder instead of Base64URL. This has been fixed in {VertX} {4}, and Base64URL encoder is used in the JSON types.

If you want to continue using the Base64 encoder in {VertX} {4}, you can use the configuration flag `legacy`. The following example shows how to set the configuration flag in {VertX} {4}.

----
java -Dvertx.json.base64=legacy ...
----

A new utility method `Json.toBase64()` converts the Base64URL string to Base64. This utility can be for:

* Handling integration while migrating from {VertX} {3x} releases to {VertX} {4}.

* Handling interoperability with other systems that use Base64 strings.

Use the following example code to convert a Base64URL to Base64 encoder.

----
String base64url = someJsonObject.getString("base64encodedElement")
String base64 = Json.toBase64(base64url);
----
