[id="changes-in-json_{context}"]
= Changes in JSON

This section describes changes in JSON.

== Encapsulation of Jackson

All the methods in the JSON class that implement Jackson types have been removed. Use the following methods instead:

[options="header"]
|===
|Removed Fields/Methods|New methods
|`Json.mapper()` field|`DatabindCodec.mapper()`
|`Json.prettyMapper()` field|`DatabindCodec.prettyMapper()`
|`Json.decodeValue(Buffer, TypeReference<T>)`|`JacksonCodec.decodeValue(Buffer, TypeReference)`
|`Json.decodeValue(String, TypeReference<T>)`|
`JacksonCodec.decodeValue(String, TypeReference)`
|===

For example, use the following code:

* When using Jackson `TypeReference`:
** In {VertX} {v3x} releases:
+
[source,java,options="nowrap",subs="attributes+"]
----
List<Foo> foo1 = Json.decodeValue(json, new TypeReference<List<Foo>>() {});
----

** In {VertX} {v4} release:
+
[source,java,options="nowrap",subs="attributes+"]
----
List<Foo> foo2 = io.vertx.core.json.jackson.JacksonCodec.decodeValue(json, new TypeReference<List<Foo>>() {});
----

* Referencing an `ObjectMapper`:

** In {VertX} {v3x} releases:
+
[source,java,options="nowrap",subs="attributes+"]
----
ObjectMapper mapper = Json.mapper;
----

** In {VertX} {v4} release:
+
[source,java,options="nowrap",subs="attributes+"]
----
mapper = io.vertx.core.json.jackson.DatabindCodec.mapper();
----

* Setting an `ObjectMapper`:

** In {VertX} {v3x} releases:
+
[source,java,options="nowrap",subs="attributes+"]
----
Json.mapper = someMapper;
----

** From {VertX} {v4} onward, you cannot write a mapper instance. You should use your own static mapper or configure the `Databind.mapper()` instance.

== Object mapping

In earlier releases, the Jackson core and Jackson databind dependencies were required at runtime.

From {VertX} {v4} onward, only the Jackson core dependency is required.

You will require the Jackson databind dependency only if you are object mapping JSON. In this case, you must explicitly add the dependency in your project descriptor in the `com.fasterxml.jackson.core:jackson-databind` jar.

The following methods are supported for the mentioned types.

* *Methods*

** `JsonObject.mapFrom(Object)`
** `JsonObject.mapTo(Class)`
** `Json.decodeValue(Buffer, Class)`
** `Json.decodeValue(String, Class)`
** `Json.encode(Object)`
** `Json.encodePrettily(Object)`
** `Json.encodeToBuffer(Object)`

* *Type*

** `JsonObject` and `JsonArray`
** `Map` and `List`
** `Number`
** `Boolean`
** `Enum`
** `byte[]` and `Buffer`
** `Instant`

The following methods are supported only with Jackson bind:

* `JsonObject.mapTo(Object)`
* `JsonObject.mapFrom(Object)`

== Base64 encoder updated to Base64URL for JSON objects and arrays

The {VertX} JSON types implement RFC-7493. In earlier releases of {VertX}, the implementation incorrectly used Base64 encoder instead of Base64URL. This has been fixed in {VertX} {v4}, and Base64URL encoder is used in the JSON types.

If you want to continue using the Base64 encoder in {VertX} {v4}, you can use the configuration flag `legacy`. The following example shows how to set the configuration flag in {VertX} {v4}.

[source,java,options="nowrap",subs="attributes+"]
----
java -Dvertx.json.base64=legacy ...
----

If you want to use both {VertX} {v3x} and {VertX} {v4} releases, you can use the following utility to convert the Base64
string to Base64URL. Since both the encodings are Base64, you will have to make minimal updates to your existing
applications.

[source,java,options="nowrap",subs="attributes+"]
----
public String toBase64(String base64Url) {
  return base64Url
    .replace('+', '-')
    .replace('/', '_');
}

public String toBase64Url(String base64) {
  return base64
    .replace('-', '+')
    .replace('_', '/');
}
----

You must use the utility methods in the following scenarios:

* Handling integration while migrating from {VertX} {v3x} releases to {VertX} {v4}.

* Handling interoperability with other systems that use Base64 strings.

Use the following example code to convert a Base64URL to Base64 encoder.

[source,java,options="nowrap",subs="attributes+"]
----
String base64url = someJsonObject.getString("base64encodedElement")
String base64 = toBase64(base64url);
----

The helper functions {toBase64} and {toBase64Url} enable only JSON migrations. If you use automatic object mapping from
JSON to a {Java} POJO in your applications, then you must create a custom object mapper to convert the Base64
string to Base64URL.

The following example shows you how to create a object mapper with custom Base64 decoder.

[source,java,options="nowrap",subs="attributes+"]
----
// simple deserializer from Base64 to byte[]
class ByteArrayDeserializer extends JsonDeserializer<byte[]> {
  ByteArrayDeserializer() {
  }

  public byte[] deserialize(JsonParser p, DeserializationContext ctxt) {
    String text = p.getText();
    return Base64.getDecoder()
      .decode(text);
  }
}

// ...

ObjectMapper mapper = new ObjectMapper();

// create a custom module to address the Base64 decoding
SimpleModule module = new SimpleModule();
module.addDeserializer(byte[].class, new ByteArrayDeserializer());
mapper.registerModule(module);

// JSON to POJO with custom deserializer
mapper.readValue(json, MyClass.class);
----

== Removed the JSON converter method from trust options

The `TrustOptions.toJSON` method has been removed.
