[id="changes-in-key-management_{context}"]
= Changes in key management

In {VertX} {4}, there are major updates in handling keys. The most important change is that when a key loads, there is no distinction between public buffer and private buffer.

The following classes have been updated:

* `io.vertx.ext.auth.KeyStoreOptions` used to work with `jce` keystores

* `io.vertx.ext.auth.SecretOptions` used to handle symmetric secrets

* `io.vertx.ext.auth.PubSecKeyOptions` used to handle public secret keys

The following section describes the changes in key management.

== Secret options class is no longer available

The `SecretOptions` class is no longer available. Use the new `PubSecKeyOptions` class instead to work with a cryptographic key.

The following example shows how methods of `SecretOptions` class were used in {VertX} {3x} releases.

----
new SecretOptions()
    .setType("HS256")
    .setSecret("password")
----

The following example shows how methods of `PubSecKeyOptions` class should be used in {VertX} {4}.

----
new PubSecKeyOptions()
    .setAlgorithm("HS256")
    .setSecretKey("password")
----

== Updates in public secret keys management

In {VertX} {3x}, the configuration object in public secret key management assumed that:

* Keys are configured as key-pairs.
* Key data is a PKCS8 encoded string without standard delimiters.

The following example shows how to configure key pair in {VertX} {3x}.

[source,java,options="nowrap",subs="attributes+"]
----
new PubSecKeyOptions()
  .setPublicKey(
    // remove the boundaries
    // (don't do this as it doesn't handle end of lines
    // it's for illustration purposes)
    pubPemString
      .replaceAll("-----BEGIN PUBLIC KEY----")
      .replaceAll("-----END PUBLIC KEY----"))
  .setSecretKey(
    // remove the boundaries
    // (don't do this as it doesn't handle end of lines
    // it's for illustration purposes)
    secPemString
      .replaceAll("-----BEGIN PUBLIC KEY----")
      .replaceAll("-----END PUBLIC KEY----"));
----

In {VertX} {4}, the configuration uses a single key, so a key-pair should be 2 key (the public
the secret)XXX.

The following example shows how to configure key pair in {VertX} {4}.

[source,java,options="nowrap",subs="attributes+"]
----
PubSecKeyOptions pubKey =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file (boundaries included)
    .setBuffer(pubPemString);

PubSecKeyOptions secKey =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file (boundaries included)
    .setBuffer(secPemString);
----

You can now handle X509 certificates using `PubSecKeyOptions`.

[source,java,options="nowrap",subs="attributes+"]
----
PubSecKeyOptions x509Certificate =
  new PubSecKeyOptions()
    // the buffer is the exact contents of the PEM file (boundaries included)
    .setBuffer(x509PemString);
----

== Changes in keystore management

In {VertX} {3x}, `KeyStoreOptions` assumes that the keystore format is `jceks`, and the stored password is the same as the password of the key. As `jceks` is a proprietary format, it is recommended to use a standard format, such as JDK, instead.

The following example shows how to load a `jceks` keystore in {VertX} {3x}.

[source,java,options="nowrap",subs="attributes+"]
----
new KeyStoreOptions()
  .setPath("path/to/keystore.jks")
  .setPassword("keystore-password");
----

In {VertX} {4}, the default format is assumed to be the default format configured by JDK. The format is `PKCS12` in Java 9 and above.

The following example shows how to load a `jceks` keystore in {VertX} {4}.

[source,java,options="nowrap",subs="attributes+"]
----
new KeyStoreOptions()
  .setPath("path/to/keystore.jks")
  // this is required as for modern JDKs this isn't the default
  // type and probaly `pkcs12` will be picked instead
  .setType("jceks")
  .setPassword("keystore-password")
  // optionally if your keys have different passwords
  // if a key specific id is not provided it defaults to
  // the keystore password
  .putPasswordProtection("key-id", "key-specific-password");
----
